version: '3.8'

services:
  agente:
    image: node:20-slim
    container_name: dieleozagent-debug-dieleozagent-1
    restart: always
    volumes:
      - .:/home/administrador/docker/agente
      - /home/administrador/docker/LFC2:/home/administrador/docker/LFC2
    working_dir: /home/administrador/docker/agente
    env_file:
      - .env
    command: node src/agent.js --vigilia

networks:
  default:
    external: true
    name: docker_sicc_net
